// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Round-trip command: shell + core metadata for the placeholder page.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if the read through managed state fails.
	 */
	shellInfo: () => typedError<ShellInfo, BusError>(__TAURI_INVOKE("shell_info")),
	/**
	 *  A command that fails **on purpose**, so the error path is demonstrated rather than
	 *  asserted only in a unit test.
	 * 
	 *  The placeholder page invokes it and renders the resulting [`BusError`]. Keeping a
	 *  deliberate-failure command on the bus means the frontend's error rendering is
	 *  exercised by every developer who opens the app, not only when something breaks.
	 * 
	 *  # Errors
	 * 
	 *  Always. That is the point.
	 */
	busSelftestFailure: () => typedError<null, BusError>(__TAURI_INVOKE("bus_selftest_failure")),
	/**
	 *  Start the demo event stream on a **per-invocation** channel.
	 * 
	 *  The `channel` argument is the whole correlation mechanism: Tauri mints one per
	 *  `invoke`, so a second run cannot reach the first run's screen.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a genuine failure; a dropped channel is reported as
	 *  `cancelled` in the [`StreamOutcome`], not as an error.
	 */
	startDemoStream: (steps: number, channel: Channel<BusEvent>) => typedError<StreamOutcome, BusError>(__TAURI_INVOKE("start_demo_stream", { steps, channel })),
	/**
	 *  Report which credential source would answer an LLM call, without exposing the
	 *  credential itself — the no-credential banner's read.
	 * 
	 *  This is `llm_credential_status`'s first production caller (`src/adapters/secrets.rs`
	 *  r1.s1.w2), which is what makes removing its `#[allow(dead_code)]` sound rather than
	 *  a bare grep of convenience: `deny(warnings)` would not let the allow come off before
	 *  a real caller existed.
	 * 
	 *  No `Result`: the read has no failure mode (an unresolvable credential reads as
	 *  [`CredentialStatus::None`], not an error), so wrapping it in one would claim a
	 *  failure mode this command does not have.
	 */
	credentialStatus: () => __TAURI_INVOKE<CredentialStatus>("credential_status"),
	/**
	 *  The Strategy Library's one read: every strategy, its version tree, per-version
	 *  stats where a persisted run exists, and each version's recent run catalog.
	 * 
	 *  A pure read — the Library writes nothing (ADR-0010); pin/archive/rename each
	 *  need a write command and are out of this item's budget.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if any repository read fails — including a corrupt
	 *  run row surfacing from the fail-closed `latest_run_for_version` (#39).
	 */
	libraryOverview: () => typedError<LibraryOverview, BusError>(__TAURI_INVOKE("library_overview")),
};

/* Types */
/**
 *  The single serializable error shape that crosses the Tauri boundary.
 * 
 *  Two fields, always both present, so the TypeScript type generated from this struct
 *  describes every error the frontend can receive.
 */
export type BusError = {
	/**  The family this error came from. */
	code: BusErrorCode,
	/**  The source error's `Display` rendering — prose, safe to show a user. */
	message: string,
};

/**
 *  Which family a [`BusError`] came from — a closed set the frontend can branch on.
 * 
 *  Serializes as a lower-case string discriminant (`"data"`, `"backtest"`, ...), never
 *  as an index, so a variant inserted later cannot renumber the existing ones.
 */
export type BusErrorCode = 
/**  The data pipeline / persistence layer (`DataError`). */
"data" | 
/**  Semantic DSL validation (`ValidationErrors`) — the correctable-rejection family. */
"validation" | 
/**  The backtest engine (`BacktestError`). */
"backtest" | 
/**  Exchange metadata (`ExchangeError`). */
"exchange" | 
/**  The LLM transport (`LlmError`). */
"llm" | 
/**  The composer agent loop (`ComposerError`). */
"composer" | 
/**  The shell itself: a dead channel, a failed startup, a bug. Not a domain family. */
"internal";

/**
 *  One event on one run's channel.
 * 
 *  `run_id` + `seq` together let the frontend detect a dropped event rather than
 *  silently rendering a shorter stream.
 */
export type BusEvent = {
	/**  The run this event belongs to — the id the command was invoked with. */
	runId: RunId,
	/**  Monotonic from 0 within a run. */
	seq: number,
	/**  What happened. */
	payload: BusEventPayload,
};

/**
 *  What a streamed event is *about*.
 * 
 *  Internally tagged on `kind`, so the frontend switches on one discriminated union
 *  rather than sniffing which optional fields are present.
 */
export type BusEventPayload = 
/**  The run has begun. Always the first event on a channel. */
{ kind: "started" } | 
/**  Incremental progress — one step, one token, one line of output. */
{ kind: "progress"; 
/**  Human-readable progress text. */
message: string } | 
/**  The run finished successfully. Always the last event on a channel. */
{ kind: "finished"; 
/**  A closing summary line. */
message: string };

/**
 *  The value-free credential read for a UI banner (r1.s1.w2 step 6) — which source
 *  answered, or that none did.
 * 
 *  This is the seam `r1.s1.w5` renders its no-credential banner from. It carries no
 *  key material at all, so it is safe to send across the Tauri IPC boundary, and it
 *  is computed without performing any LLM request.
 * 
 *  `specta::Type` (r1.s1.w5): this is the one domain type that crosses the Tauri
 *  boundary directly rather than through a `src/tauri/`-ring wire type — it already IS
 *  the value-free wire shape the banner needs, so a wrapper struct would add a
 *  translation step with nothing to translate.
 */
export type CredentialStatus = 
/**  The process environment answered. */
"env" | 
/**  `$PULSE_CONFIG_DIR/.env` answered. */
"config-dir" | 
/**  A working-directory / manifest-directory `.env` answered. */
"cwd-dotenv" | 
/**  The application data directory's `.env` answered. */
"app-data-dir" | 
/**
 *  No usable credential — absent everywhere, or found but REFUSED by the
 *  permission checks. Both read as "not usable", which is what a banner needs.
 */
"none";

/**
 *  A version's DSL rendered to summary lines — exactly the fields
 *  [`StrategyDsl`] carries, nothing more.
 */
export type DslSummary = {
	/**  The document's name. */
	name: string,
	/**  `"long"` or `"short"`. */
	direction: string,
	/**  The entry trigger, one line (the DSL's `entry` is a single condition). */
	entry: string[],
	/**  The gating filters, one line each. */
	filters: string[],
	/**  The exit rules, one line each. */
	exits: string[],
	/**  The risk parameters, one line each. */
	risk: string[],
};

/**
 *  The `library_overview` command's whole payload: every strategy, each with its
 *  version tree.
 */
export type LibraryOverview = {
	/**  Every persisted strategy, in the repository's list order. */
	strategies: LibraryStrategy[],
};

/**  One row of a version's run catalog (`list_runs_for_version`'s projection). */
export type LibraryRunSummary = {
	/**  The run's id. */
	id: string,
	/**  Run timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Completed trades in the run. */
	trades: number,
};

/**  One strategy and its `version_tree`-ordered versions. */
export type LibraryStrategy = {
	/**  The strategy's id. */
	id: string,
	/**  The strategy's name. */
	name: string,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The pinned version's id, if the strategy has one (FR-11 pin). */
	pinnedVersionId: string | null,
	/**  All versions, parent-before-child (`version_tree` order). */
	versions: LibraryVersion[],
};

/**  One version: tree position, DSL summary, stats-or-em-dash, recent runs. */
export type LibraryVersion = {
	/**  The version's id. */
	id: string,
	/**  The parent version's id (`None` for a root). */
	parentId: string | null,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The version's DSL, rendered to summary lines. */
	dsl: DslSummary,
	/**
	 *  The latest persisted run's stats, or `None` when no run exists — the
	 *  screen renders an em dash on `None` (grill A1).
	 */
	stats: VersionStats | null,
	/**
	 *  The expectancy delta vs the parent's, formatted (e.g. `"+0.12R"`), when
	 *  BOTH this version and its parent carry a run. `None` otherwise.
	 */
	deltaVsParent: string | null,
	/**
	 *  This version's run catalog (best-effort — one corrupt row costs its row
	 *  here, not the screen), newest first.
	 */
	recentRuns: LibraryRunSummary[],
};

/**
 *  A per-invocation run identifier, minted when a streaming command starts.
 * 
 *  Opaque on the wire (`#[serde(transparent)]` over a UUID string) so the frontend
 *  compares it and never parses it.
 */
export type RunId = string;

/**
 *  The metadata the placeholder page renders — the one round-trip command this work
 *  item ships.
 * 
 *  Deliberately boring: no credential and no LLM-derived data crosses this boundary, so
 *  no risk gate fires on this item. `r1.s1.w4` is where that changes and it carries the
 *  controls.
 */
export type ShellInfo = {
	/**  The crate version this bundle was built from. */
	appVersion: string,
	/**  The build-time `engine_fingerprint` (FR-7) — proves the GUI and CLI share one core. */
	engineFingerprint: string,
	/**  The compiled target triple. */
	targetTriple: string,
	/**  How many strategies the database holds — a real read through managed state. */
	strategyCount: number,
};

/**  How a streaming run ended. */
export type StreamOutcome = {
	/**  The run this outcome describes. */
	runId: RunId,
	/**  How many events actually reached the far end. */
	emitted: number,
	/**  True when the far end went away mid-run (the screen unmounted). */
	cancelled: boolean,
};

/**
 *  The three headline KPIs the screen renders per version, pre-formatted from
 *  the persisted run's [`SummaryStats`].
 */
export type VersionStats = {
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Fraction of winners, e.g. `"48.3%"`. */
	winRate: string,
	/**  Completed trades in the run. */
	trades: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

