// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Round-trip command: shell + core metadata for the placeholder page.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if the read through managed state fails.
	 */
	shellInfo: () => typedError<ShellInfo, BusError>(__TAURI_INVOKE("shell_info")),
	/**
	 *  A command that fails **on purpose**, so the error path is demonstrated rather than
	 *  asserted only in a unit test.
	 * 
	 *  The placeholder page invokes it and renders the resulting [`BusError`]. Keeping a
	 *  deliberate-failure command on the bus means the frontend's error rendering is
	 *  exercised by every developer who opens the app, not only when something breaks.
	 * 
	 *  # Errors
	 * 
	 *  Always. That is the point.
	 */
	busSelftestFailure: () => typedError<null, BusError>(__TAURI_INVOKE("bus_selftest_failure")),
	/**
	 *  Start the demo event stream on a **per-invocation** channel.
	 * 
	 *  The `channel` argument is the whole correlation mechanism: Tauri mints one per
	 *  `invoke`, so a second run cannot reach the first run's screen.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a genuine failure; a dropped channel is reported as
	 *  `cancelled` in the [`StreamOutcome`], not as an error.
	 */
	startDemoStream: (steps: number, channel: Channel<BusEvent>) => typedError<StreamOutcome, BusError>(__TAURI_INVOKE("start_demo_stream", { steps, channel })),
	/**
	 *  Report which credential source would answer an LLM call, without exposing the
	 *  credential itself — the no-credential banner's read.
	 * 
	 *  This is `llm_credential_status`'s first production caller (`src/adapters/secrets.rs`
	 *  r1.s1.w2), which is what makes removing its `#[allow(dead_code)]` sound rather than
	 *  a bare grep of convenience: `deny(warnings)` would not let the allow come off before
	 *  a real caller existed.
	 * 
	 *  No `Result`: the read has no failure mode (an unresolvable credential reads as
	 *  [`CredentialStatus::None`], not an error), so wrapping it in one would claim a
	 *  failure mode this command does not have.
	 */
	credentialStatus: () => __TAURI_INVOKE<CredentialStatus>("credential_status"),
	/**
	 *  The Strategy Library's one read: every strategy, its version tree, per-version
	 *  stats where a persisted run exists, and each version's recent run catalog.
	 * 
	 *  A pure read — the Library writes nothing (ADR-0010); pin/archive/rename each
	 *  need a write command and are out of this item's budget.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if any repository read fails — including a corrupt
	 *  run row surfacing from the fail-closed `latest_run_for_version` (#39).
	 */
	libraryOverview: () => typedError<LibraryOverview, BusError>(__TAURI_INVOKE("library_overview")),
	/**
	 *  Compose a strategy from a natural-language target, streaming the composer's
	 *  tool-call steps over a **per-invocation** channel (grill A2 — the channel is
	 *  the correlation) until the run finalizes and a persisted, attributable
	 *  `StrategyVersion` exists.
	 * 
	 *  **Nothing but the target crosses the boundary in, and no credential crosses
	 *  it in any direction, ever** (ADR-0016, the risk gate's IPC half): the key
	 *  resolves INSIDE the ring via [`resolve_llm_api_key`], `key.expose()` reaches
	 *  exactly two consumers (the provider constructor and `Redactor::from_config`),
	 *  and the credential-source LABEL is captured before either — the live arm's
	 *  key discipline (`src/cli/compose.rs`), mirrored.
	 * 
	 *  An unresolvable credential is a [`BusError`] carrying the resolver's own
	 *  message — it names every searched location and fails closed (`w2`); the
	 *  screen renders it, and `w5`'s banner already states the condition globally.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a config-load failure, an unresolvable credential,
	 *  or a genuine compose/persist failure. A dropped channel is reported as
	 *  `cancelled` in the [`ComposeResult`], not as an error.
	 */
	composeStrategy: (nlTarget: string, channel: Channel<BusEvent>) => typedError<ComposeResult, BusError>(__TAURI_INVOKE("compose_strategy", { nlTarget, channel })),
	/**
	 *  Cancel an in-flight compose run by id.
	 * 
	 *  The Designer fires this from its unmount cleanup. Without it, navigating away
	 *  mid-compose left the run streaming into a channel nobody read: the JavaScript
	 *  `Channel`'s callback stays registered with Tauri for the life of the webview, so
	 *  every send kept SUCCEEDING, the failed-send guard never tripped, and the
	 *  remaining billable LLM calls ran to completion and persisted a strategy the user
	 *  had already walked away from.
	 * 
	 *  Tripping the latch makes [`RefusingProvider`] refuse at the run's next model turn,
	 *  so the run stops within one LLM call and persists nothing.
	 * 
	 *  Returns whether a run by that id was in flight. `false` is an ordinary outcome —
	 *  the run may have finished between the frontend deciding to cancel and this command
	 *  arriving — not an error, so the Designer's cleanup needs no failure path.
	 * 
	 *  # Errors
	 * 
	 *  Never. The `Result` is the bus's uniform command shape.
	 */
	composeCancel: (runId: string) => typedError<boolean, BusError>(__TAURI_INVOKE("compose_cancel", { runId })),
};

/* Types */
/**
 *  The single serializable error shape that crosses the Tauri boundary.
 * 
 *  Two fields, always both present, so the TypeScript type generated from this struct
 *  describes every error the frontend can receive.
 */
export type BusError = {
	/**  The family this error came from. */
	code: BusErrorCode,
	/**  The source error's `Display` rendering — prose, safe to show a user. */
	message: string,
};

/**
 *  Which family a [`BusError`] came from — a closed set the frontend can branch on.
 * 
 *  Serializes as a lower-case string discriminant (`"data"`, `"backtest"`, ...), never
 *  as an index, so a variant inserted later cannot renumber the existing ones.
 */
export type BusErrorCode = 
/**  The data pipeline / persistence layer (`DataError`). */
"data" | 
/**  Semantic DSL validation (`ValidationErrors`) — the correctable-rejection family. */
"validation" | 
/**  The backtest engine (`BacktestError`). */
"backtest" | 
/**  Exchange metadata (`ExchangeError`). */
"exchange" | 
/**  The LLM transport (`LlmError`). */
"llm" | 
/**  The composer agent loop (`ComposerError`). */
"composer" | 
/**  The shell itself: a dead channel, a failed startup, a bug. Not a domain family. */
"internal";

/**
 *  One event on one run's channel.
 * 
 *  `run_id` + `seq` together let the frontend detect a dropped event rather than
 *  silently rendering a shorter stream.
 */
export type BusEvent = {
	/**  The run this event belongs to — the id the command was invoked with. */
	runId: RunId,
	/**  Monotonic from 0 within a run. */
	seq: number,
	/**  What happened. */
	payload: BusEventPayload,
};

/**
 *  What a streamed event is *about*.
 * 
 *  Internally tagged on `kind`, so the frontend switches on one discriminated union
 *  rather than sniffing which optional fields are present.
 */
export type BusEventPayload = 
/**  The run has begun. Always the first event on a channel. */
{ kind: "started" } | 
/**  Incremental progress — one step, one token, one line of output. */
{ kind: "progress"; 
/**  Human-readable progress text. */
message: string } | 
/**
 *  A composer tool call was dispatched to a builder tool (r1.s1.w4).
 * 
 *  Mirrors [`ComposerEvent::ToolCallStarted`](crate::agent::ComposerEvent):
 *  the payload carries the composer's OWN fields — the tool name and its
 *  non-secret arguments preview — never invented ones. Mapping the composer's
 *  stream onto the channel is rendering, not faking.
 * 
 *  The variant-level `rename_all` exists because the ENUM-level one renames
 *  variants only, not their fields — without it `arguments_preview` would
 *  cross the wire in `snake_case` against the file's `camelCase` convention
 *  (a nothing-word like `message` never exposed this before multi-word
 *  fields).
 */
{ kind: "toolCallStarted"; 
/**  The builder tool the model called (e.g. `add_filter`). */
name: string; 
/**  A short, non-secret preview of the call arguments. */
argumentsPreview: string } | 
/**
 *  A composer tool call produced an outcome (r1.s1.w4).
 * 
 *  Mirrors [`ComposerEvent::ToolCallResult`](crate::agent::ComposerEvent) —
 *  the `Ok` summary or the serialized correctable `FieldError`s, appended to
 *  the same step its `ToolCallStarted` opened.
 */
{ kind: "toolCallResult"; 
/**  The builder tool the model called. */
name: string; 
/**  The `Ok` summary or the serialized correctable errors. */
outcome: string } | 
/**
 *  The run finished successfully. Always the last event on a channel.
 * 
 *  For a compose run (r1.s1.w4) the closing summary is the composer's own
 *  finalize line — `ComposerEvent::Finalized`'s `version_summary`.
 */
{ kind: "finished"; 
/**  A closing summary line. */
message: string };

/**
 *  The compact DSL summary a finalized run returns — the finalize summary
 *  card's data, rendered from the fields the persisted version actually
 *  carries (the `w3` "real fields" discipline: render what the DSL carries,
 *  omit what it does not).
 * 
 *  Lines, not structures, on purpose: the ring renders the DSL's own values
 *  into mono summary lines and the screen never parses strategy JSON.
 */
export type ComposeDslSummary = {
	/**  The trade side, `"long"` / `"short"` — the DSL's own `Direction` value. */
	direction: string,
	/**  The required entry trigger, e.g. `rsi(14) < 30`. */
	entry: string,
	/**  The gating conditions conjoined with the entry, one line each. */
	filters: string[],
	/**  The exit rules, one line each (e.g. `stop_loss 5%`, `take_profit 2R`). */
	exits: string[],
	/**  The risk / sizing inputs, one line each. */
	risk: string[],
};

/**
 *  The outcome of one compose run — [`StreamOutcome`]'s shape (a run id, what
 *  actually crossed, cancellation) extended with the finalize payload.
 * 
 *  `strategy` is `None` exactly when the run did not finalize: a cancelled run
 *  (the screen went away) carries no summary because nothing persisted.
 */
export type ComposeResult = {
	/**  The run this outcome describes. */
	runId: RunId,
	/**  How many events actually reached the far end. */
	emitted: number,
	/**  True when the far end went away mid-run (the screen unmounted). */
	cancelled: boolean,
	/**  The persisted strategy summary — present iff the run finalized. */
	strategy: ComposeStrategySummary | null,
};

/**  What a finalized compose run reports about the strategy it persisted. */
export type ComposeStrategySummary = {
	/**  The persisted strategy's repo-minted id. */
	strategyId: string,
	/**  The strategy's name (the DSL's own `name`). */
	strategyName: string,
	/**  The persisted initial version's repo-minted id. */
	versionId: string,
	/**
	 *  Who authored the version — the `strategy_version.created_by` label
	 *  (`"composer_llm"` for this run; the pinned serialization strings).
	 */
	createdBy: string,
	/**  How many `LlmCall`s produced this version (its provenance count). */
	llmCallCount: number,
	/**  The compact DSL summary rendered above. */
	dsl: ComposeDslSummary,
};

/**
 *  The value-free credential read for a UI banner (r1.s1.w2 step 6) — which source
 *  answered, or that none did.
 * 
 *  This is the seam `r1.s1.w5` renders its no-credential banner from. It carries no
 *  key material at all, so it is safe to send across the Tauri IPC boundary, and it
 *  is computed without performing any LLM request.
 * 
 *  `specta::Type` (r1.s1.w5): this is the one domain type that crosses the Tauri
 *  boundary directly rather than through a `src/tauri/`-ring wire type — it already IS
 *  the value-free wire shape the banner needs, so a wrapper struct would add a
 *  translation step with nothing to translate.
 */
export type CredentialStatus = 
/**  The process environment answered. */
"env" | 
/**  `$PULSE_CONFIG_DIR/.env` answered. */
"config-dir" | 
/**  A working-directory / manifest-directory `.env` answered. */
"cwd-dotenv" | 
/**  The application data directory's `.env` answered. */
"app-data-dir" | 
/**
 *  No usable credential — absent everywhere, or found but REFUSED by the
 *  permission checks. Both read as "not usable", which is what a banner needs.
 */
"none";

/**
 *  A version's DSL rendered to summary lines — exactly the fields
 *  [`StrategyDsl`] carries, nothing more.
 */
export type DslSummary = {
	/**  The document's name. */
	name: string,
	/**  `"long"` or `"short"`. */
	direction: string,
	/**  The entry trigger, one line (the DSL's `entry` is a single condition). */
	entry: string[],
	/**  The gating filters, one line each. */
	filters: string[],
	/**  The exit rules, one line each. */
	exits: string[],
	/**  The risk parameters, one line each. */
	risk: string[],
};

/**
 *  The `library_overview` command's whole payload: every strategy, each with its
 *  version tree.
 */
export type LibraryOverview = {
	/**  Every persisted strategy, in the repository's list order. */
	strategies: LibraryStrategy[],
};

/**  One row of a version's run catalog (`list_runs_for_version`'s projection). */
export type LibraryRunSummary = {
	/**  The run's id. */
	id: string,
	/**  Run timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Completed trades in the run. */
	trades: number,
};

/**  One strategy and its `version_tree`-ordered versions. */
export type LibraryStrategy = {
	/**  The strategy's id. */
	id: string,
	/**  The strategy's name. */
	name: string,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The pinned version's id, if the strategy has one (FR-11 pin). */
	pinnedVersionId: string | null,
	/**  All versions, parent-before-child (`version_tree` order). */
	versions: LibraryVersion[],
};

/**  One version: tree position, DSL summary, stats-or-em-dash, recent runs. */
export type LibraryVersion = {
	/**  The version's id. */
	id: string,
	/**  The parent version's id (`None` for a root). */
	parentId: string | null,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The version's DSL, rendered to summary lines. */
	dsl: DslSummary,
	/**
	 *  The latest persisted run's stats, or `None` when no run exists — the
	 *  screen renders an em dash on `None` (grill A1).
	 */
	stats: VersionStats | null,
	/**
	 *  The expectancy delta vs the parent's, formatted (e.g. `"+0.12R"`), when
	 *  BOTH this version and its parent carry a run. `None` otherwise.
	 */
	deltaVsParent: string | null,
	/**
	 *  This version's run catalog (best-effort — one corrupt row costs its row
	 *  here, not the screen), newest first.
	 */
	recentRuns: LibraryRunSummary[],
};

/**
 *  A per-invocation run identifier, minted when a streaming command starts.
 * 
 *  Opaque on the wire (`#[serde(transparent)]` over a UUID string) so the frontend
 *  compares it and never parses it.
 */
export type RunId = string;

/**
 *  The metadata the placeholder page renders — the one round-trip command this work
 *  item ships.
 * 
 *  Deliberately boring: no credential and no LLM-derived data crosses this boundary, so
 *  no risk gate fires on this item. `r1.s1.w4` is where that changes and it carries the
 *  controls.
 */
export type ShellInfo = {
	/**  The crate version this bundle was built from. */
	appVersion: string,
	/**  The build-time `engine_fingerprint` (FR-7) — proves the GUI and CLI share one core. */
	engineFingerprint: string,
	/**  The compiled target triple. */
	targetTriple: string,
	/**  How many strategies the database holds — a real read through managed state. */
	strategyCount: number,
};

/**  How a streaming run ended. */
export type StreamOutcome = {
	/**  The run this outcome describes. */
	runId: RunId,
	/**  How many events actually reached the far end. */
	emitted: number,
	/**  True when the far end went away mid-run (the screen unmounted). */
	cancelled: boolean,
};

/**
 *  The three headline KPIs the screen renders per version, pre-formatted from
 *  the persisted run's [`SummaryStats`].
 */
export type VersionStats = {
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Fraction of winners, e.g. `"48.3%"`. */
	winRate: string,
	/**  Completed trades in the run. */
	trades: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

